# Generated by Django 3.2.10 on 2022-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marklist',
            fields=[
                ('ROLLNO', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(blank=True, max_length=100)),
                ('STANDARD', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
