# Generated by Django 3.2.10 on 2022-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='Chemistry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marklist',
            name='Maths',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marklist',
            name='Physics',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
